import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1400,height:900}}),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.text().includes('[vite]'))console.log(msg.text());});
 await mkdir('benchmark-runs/checks/emerald-workbench',{recursive:true});
 // Keep this recipe on the source loaded by its explicit navigation; concurrent HMR edits must not erase a running campaign.
 await page.routeWebSocket('**',socket=>{const server=socket.connectToServer();server.onMessage(message=>{let type;try{type=JSON.parse(String(message)).type;}catch{}if(type!=='update'&&type!=='full-reload')socket.send(message);});socket.onMessage(message=>server.send(message));});
 await page.goto('http://localhost:5174/?test=15-virtualized-integration');
 const ready=async()=>{await page.locator('[data-emerald-availability="ready"]').waitFor({timeout:30000});assert.equal(await page.locator('canvas').count(),0);};
 await ready();
 const extentName={1:'1 ville',4:'4 villes',9:'9 villes'};
 const configure=async(cities,diagnostic,mode='explore',camera='orbit')=>{await page.getByRole('radio',{name:extentName[cities]}).click();await page.getByRole('radio',{name:'Anisotropie maximale'}).click();await page.getByRole('radio',{name:mode==='path'?'Parcours urbain reproductible':'Exploration libre'}).click();if(mode==='explore'){await page.getByLabel('Caméra',{exact:true}).selectOption(camera);await page.getByLabel('Vue de diagnostic',{exact:true}).selectOption(diagnostic);}else{assert.equal(await page.locator('#lab-mode-card').count(),0);}};
 const launch=async()=>{await page.locator('main').getByRole('button',{name:/^(Explorer Emerald Square|Lancer le parcours urbain)$/}).click();await page.locator('[data-ui-state="loading"]').waitFor();await page.locator('[data-emerald-status="ready"], [data-emerald-status="error"]').waitFor({timeout:180000});assert.equal(await page.locator('[data-emerald-status]').getAttribute('data-emerald-status'),'ready',await page.locator('main').innerText());assert.ok(await page.locator('#canvas-emerald').isVisible());assert.equal(await page.locator('#emerald-extent').count(),0);};
 const stop=async()=>{await page.getByRole('button',{name:'Arrêter l’exploration',exact:true}).click();await page.locator('[data-emerald-report]').waitFor();assert.equal(await page.locator('canvas').count(),0);};
 const next=async()=>{await page.locator('main').getByRole('button',{name:'Nouvelle exécution',exact:true}).click();await ready();};
 for(const [cities,diagnostic,camera] of [[1,'beauty','orbit'],[4,'beauty','free'],[9,'beauty','orbit'],[1,'wireframe','orbit'],[1,'clusters','orbit'],[1,'pages','orbit']]){
  await configure(cities,diagnostic,'explore',camera);await launch();await page.waitForTimeout(1300);
  assert.equal(await page.locator('[data-emerald-status]').getAttribute('data-emerald-status'),'ready',await page.locator('main').innerText());const canvas=page.locator('#canvas-emerald'),before=await canvas.screenshot({path:`benchmark-runs/checks/emerald-workbench/${cities}-${diagnostic}.png`});
  const box=await canvas.boundingBox();assert.ok(box.height>300);
  if(camera==='free'){await canvas.focus();await page.keyboard.down('KeyW');await page.waitForTimeout(700);await page.keyboard.up('KeyW');assert.notDeepEqual(before,await canvas.screenshot(),'free movement changes pixels');}
  assert.equal(await page.locator('[data-emerald-engine-bar]').count(),0);
  assert.equal(await page.locator('#emerald-compare-engine').count(),0);
  assert.equal(await page.locator('#emerald-layout').count(),0);
  if(diagnostic==='clusters'||diagnostic==='pages'){await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.wheel(0,-900);await page.waitForTimeout(1200);assert.notDeepEqual(before,await canvas.screenshot());}
  await stop();const report=await page.evaluate(()=>JSON.parse(localStorage.getItem('render-tech-lab:emerald-runs:v1'))[0]);assert.equal(report.availableTriangles,10046405*cities);assert.ok(report.firstImageMs>0);assert.equal(report.configuration.detail,'maximum');assert.equal(report.error,null);if(diagnostic==='clusters'||diagnostic==='pages'){assert.ok(report.samples.some(s=>s.clusters>0));assert.ok(report.samples.some(s=>s.residentPages>0));assert.ok(report.samples.every(s=>s.backend==='exact-cluster-pages'));assert.ok(new Set(report.samples.map(s=>s.clusters)).size>1,'camera changes actual selected clusters');assert.ok(report.samples.some(s=>s.pageEvictions>0),'camera evicts real attached pages');}
  results.push({cities,diagnostic,firstImageMs:report.firstImageMs,samples:report.samples.length,triangles:report.samples.at(-1)?.triangles,clusters:report.samples.at(-1)?.clusters,residentPages:report.samples.at(-1)?.residentPages});console.log('PASS',cities,diagnostic);await next();
 }
 await configure(1,'beauty','path');await launch();await page.locator('[data-emerald-status="completed"], [data-emerald-status="error"]').waitFor({timeout:180000});assert.equal(await page.locator('[data-emerald-status]').getAttribute('data-emerald-status'),'completed',await page.locator('main').innerText());
 const history=await page.evaluate(()=>JSON.parse(localStorage.getItem('render-tech-lab:emerald-runs:v1')));assert.equal(history.length,5);assert.deepEqual(history[0].pathEngines,['three-webgl-reference','exact-cluster-pages','three-lod']);assert.equal(history[0].samples.length,1800);assert.equal(history[0].captures.length,30);assert.equal(history[0].warmupFrames,90);assert.equal(new Set(history[0].samples.map(s=>s.segment)).size,10);assert.ok(history[0].samples.every(s=>s.gpuMs===null));assert.ok(history[0].captures.every(still=>still.pose&&still.engine&&still.gpuMs===null));await page.screenshot({path:'benchmark-runs/checks/emerald-workbench/report.png'});await writeFile('benchmark-runs/checks/emerald-workbench/path.json',JSON.stringify(history[0],null,2));results.push({path:true,samples:1800,captures:30,history:5});console.log('PASS path and five reports');
 await next();await page.getByRole('radio',{name:'Fixture procédurale'}).click();await page.locator('[data-execution-view="idle"]').waitFor();assert.equal(await page.locator('canvas').count(),0);await page.locator('main').getByRole('button',{name:'Exécuter les 3 contrôles',exact:true}).click();await page.locator('[data-execution-view="completed"]').waitFor({timeout:90000});await page.locator('main').getByRole('button',{name:'Nouvelle exécution',exact:true}).click();await page.locator('[data-execution-view="idle"]').waitFor();await page.getByRole('radio',{name:'Emerald Square'}).click();await ready();assert.equal(await page.locator('#lab-report-card button').count(),5);assert.deepEqual(errors,[]);
 await writeFile('benchmark-runs/checks/emerald-workbench/result.json',JSON.stringify({results,errors},null,2));console.log('PASS Emerald → fixture campaign → new execution → Emerald without reload');
}finally{await browser.close();}
