import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const origin=process.env.LAB_URL??'http://127.0.0.1:5174';
const routes=['06-meshlet-culling','07-hiz','08-occlusion-culling','09-gpu-compaction','10-material-batching','11-geometry-streaming','12-visibility-buffer','13-full-gpu-driven','14-open-world'];
const dual=new Set(['01-indirect-draw','03-gpu-scene','04-gpu-lod','14-open-world']);
const browser=await chromium.launch({headless:true});
try{const page=await browser.newPage({viewport:{width:1400,height:900},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(String(e)));
for(const moduleId of routes){await page.goto(`${origin}/?test=${moduleId}`);await page.locator('#sidebar').waitFor();await page.locator(moduleId==='00-baseline'?'[aria-label="Référence de consultation"]':'[data-execution-view="idle"]').waitFor({timeout:15000});assert.equal(await page.locator('canvas').count(),0,`${moduleId}: canvas au repos`);const sidebar=await page.locator('#sidebar').innerText();if(moduleId!=='04-gpu-lod')assert.doesNotMatch(sidebar,/Même rendu natif|sélection LOD|A · Calcul CPU|B · Calcul GPU|Comparaison native/i,`${moduleId}: contenu 04`);if(moduleId!=='00-baseline'&&!dual.has(moduleId)){assert.equal(await page.locator('#btn-classic,#btn-gpu-driven').count(),0,`${moduleId}: A/B décoratif`);assert.doesNotMatch(sidebar,/Commutez instantanément entre les pipelines/i,`${moduleId}: aide fausse`);}if(moduleId==='00-baseline')continue;await page.locator('#btn-benchmark').click();await page.locator('[data-execution-view="completed"],[data-execution-view="error"],[data-execution-view="stopped"]').first().waitFor({timeout:120000});await page.waitForFunction(()=>document.querySelectorAll('canvas').length===0,null,{timeout:5000});const canvases=await page.locator('canvas').evaluateAll(nodes=>nodes.map(node=>node.id));assert.deepEqual(canvases,[],`${moduleId}: canvas après terminaison`);assert.equal(await page.getByRole('button',{name:'Relancer',exact:true}).count(),2,`${moduleId}: Relancer`);assert.equal(await page.getByRole('button',{name:'Nouvelle exécution',exact:true}).count(),1,`${moduleId}: Nouvelle exécution`);await page.getByRole('button',{name:'Nouvelle exécution',exact:true}).click();await page.locator('[data-execution-view="idle"]').waitFor();console.log(`${moduleId}: cycle validé`);}assert.deepEqual(errors,[]);
}finally{await browser.close();}
