// UI verification using the actual interactive renderer; no performance comparison or archive is produced.
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const out=process.env.LAYOUT_OUTPUT??'/tmp';
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 page.setDefaultTimeout(45000);
 page.on('pageerror',error=>errors.push(String(error)));
 await page.goto((process.env.LAB_URL??'http://localhost:5174')+'/?test=16-lighting-transport');
 await page.locator('[data-execution-view="idle"]').waitFor();
 assert.equal(await page.locator('canvas').count(),0);
 assert.match(await page.locator('main').innerText(),/Canvas prévu\s*WebGL/);
 assert.equal(await page.locator('#lighting-report-history').count(),0);
 assert.doesNotMatch(await page.locator('#sidebar').innerText(),/campagne/i);
 await page.screenshot({path:out+'/banc16-fiche-commune.png'});
 await page.locator('#btn-benchmark').click();
 await page.waitForFunction(()=>!!window.lightingBench16?.snapshot().frame,null,{timeout:120000});
 assert.equal(await page.locator('[data-render-loading]').count(),0);
 assert.equal(await page.getByRole('button',{name:'Arrêter l’exploration',exact:true}).count(),1);
 const surface=await page.locator('#canvas-webgl').evaluate(canvas=>{
   const viewport=document.querySelector('#viewport-container').getBoundingClientRect();
   const rect=canvas.getBoundingClientRect();
   return {fit:getComputedStyle(canvas).objectFit,width:rect.width,height:rect.height,viewportWidth:viewport.width,viewportHeight:viewport.height,pixels:[canvas.width,canvas.height]};
 });
 assert.equal(surface.fit,'cover');
 assert.equal(surface.width,surface.viewportWidth);assert.equal(surface.height,surface.viewportHeight);
 assert.deepEqual(surface.pixels,[Math.round(surface.width),Math.round(surface.height)]);
 assert.equal(await page.locator('#lighting-run-kind').isDisabled(),true);
 assert.equal(await page.locator('#lab-report-card').count(),0);
 await page.screenshot({path:out+'/banc16-scene-commune.png'});
 await page.setViewportSize({width:980,height:760});
 await page.waitForFunction(()=>{const canvas=document.querySelector('#canvas-webgl');const box=canvas.getBoundingClientRect();return canvas.width===Math.round(box.width)&&canvas.height===Math.round(box.height);});
 await page.setViewportSize({width:1440,height:1040});
 console.log(JSON.stringify({phase:'real-render',surface,frame:await page.evaluate(()=>window.lightingBench16.snapshot().frame)}));
 await page.getByRole('button',{name:'Arrêter l’exploration',exact:true}).click();
 await page.locator('[data-execution-view="stopped"]').waitFor();
 assert.doesNotMatch(await page.locator('#lab-run-card').innerText(),/Mesurer A\/B|Aucune campagne mesurée|campagne interrompue/);
 await page.locator('#lighting-run-kind').selectOption('comparison');
 assert.doesNotMatch(await page.locator('#lab-run-card').innerText(),/Mesurer A\/B|Aucune campagne mesurée/);
 assert.equal(await page.locator('canvas').count(),0);
 assert.equal(await page.evaluate(()=>!!window.lightingBench16),false);
 await page.getByRole('button',{name:'Voir le rapport',exact:true}).waitFor();
 await page.waitForFunction(()=>!Array.from(document.querySelectorAll('main button')).find(button=>button.textContent?.trim()==='Voir le rapport')?.disabled);
 await page.screenshot({path:out+'/banc16-arret-commun.png'});
 await page.waitForFunction(()=>!document.querySelector('#btn-view-report')?.disabled);
 await page.getByRole('button',{name:'Voir le rapport',exact:true}).click();
 await page.locator('#report-modal[open]').waitFor();
 await page.waitForFunction(()=>document.querySelector('#modal-report-body')?.textContent.includes('Banc 16 · Lumière'));
 await page.screenshot({path:out+'/banc16-rapport-commun.png'});
 await page.locator('#btn-close-modal').click();
 await page.getByRole('button',{name:'Nouvelle exécution',exact:true}).click();
 await page.locator('[data-execution-view="idle"]').waitFor();
 await page.reload();
 await page.waitForFunction(()=>!document.querySelector('#btn-view-report')?.disabled);
 await page.locator('#btn-view-report').click();
 await page.waitForFunction(()=>document.querySelector('#modal-report-body')?.textContent.includes('Banc 16 · Lumière'));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({phase:'passed',checks:['idle','real-render','single-stop','shared-surface','stopped','report','new-execution','report-after-reload'],errors,out}));
} finally {await browser.close();}
