import { VIRTUALIZED_MODULE } from '../../15-virtualized-integration/index.ts';
import { LIGHTING_MODULE } from '../../16-lighting-transport/index.ts';
import type { SceneStressConfig } from '../../03-gpu-scene/index.ts';
import type { ModuleDescriptor } from '../../shared/contracts/presentation.ts';

// Configurations prédéfinies pour le stress 4D de 03-gpu-scene
export const GPU_SCENE_PRESETS: { [key: string]: SceneStressConfig } = {
  'dim-a-10': {
    name: 'Dim A : 10 topologies',
    dimension: 'A-geometry',
    objectCount: 2000,
    geometryCount: 10,
    materialCount: 10,
    dynamicRatio: 0.1,
    targetVisibility: 1.0,
  },
  'dim-a-100': {
    name: 'Dim A : 100 topologies',
    dimension: 'A-geometry',
    objectCount: 2000,
    geometryCount: 100,
    materialCount: 10,
    dynamicRatio: 0.1,
    targetVisibility: 1.0,
  },
  'dim-b-10': {
    name: 'Dim B : 10 matériaux',
    dimension: 'B-material',
    objectCount: 2000,
    geometryCount: 10,
    materialCount: 10,
    dynamicRatio: 0.1,
    targetVisibility: 1.0,
  },
  'dim-b-100': {
    name: 'Dim B : 100 matériaux',
    dimension: 'B-material',
    objectCount: 2000,
    geometryCount: 10,
    materialCount: 100,
    dynamicRatio: 0.1,
    targetVisibility: 1.0,
  },
  'dim-c-25': {
    name: 'Dim C : 25% dynamique',
    dimension: 'C-dynamic',
    objectCount: 2000,
    geometryCount: 10,
    materialCount: 10,
    dynamicRatio: 0.25,
    targetVisibility: 1.0,
  },
  'dim-c-50': {
    name: 'Dim C : 50% dynamique',
    dimension: 'C-dynamic',
    objectCount: 2000,
    geometryCount: 10,
    materialCount: 10,
    dynamicRatio: 0.50,
    targetVisibility: 1.0,
  },
  'dim-c-100': {
    name: 'Dim C : 100% dynamique',
    dimension: 'C-dynamic',
    objectCount: 2000,
    geometryCount: 10,
    materialCount: 10,
    dynamicRatio: 1.0,
    targetVisibility: 1.0,
  },
  'dim-d-50': {
    name: 'Dim D : 50% visibilité',
    dimension: 'D-visibility',
    objectCount: 2000,
    geometryCount: 10,
    materialCount: 10,
    dynamicRatio: 0.1,
    targetVisibility: 0.5,
  },
  'pain-500': {
    name: 'Pain : 500 topologies',
    dimension: 'A-geometry',
    objectCount: 5000,
    geometryCount: 500,
    materialCount: 50,
    dynamicRatio: 0.1,
    targetVisibility: 1.0,
  },
  'pain-1000': {
    name: 'Torture : 1 000 topologies',
    dimension: 'A-geometry',
    objectCount: 10000,
    geometryCount: 1000,
    materialCount: 100,
    dynamicRatio: 0.1,
    targetVisibility: 1.0,
  },
};

// Configurations étalon Spec 13 pour 00-baseline
export const BASELINE_00_SCENARIOS: Record<
  string,
  { objects: string; submit: string; cpuFrame: string; fps: string; drawCalls: string; desc: string }
> = {
  S0: { objects: '1', submit: '0.08 ms', cpuFrame: '0.25 ms', fps: '60 FPS', drawCalls: '3', desc: 'S0 · Baseline minimale (1 objet unique, témoin zéro).' },
  S1: { objects: '500', submit: '0.12 ms', cpuFrame: '0.45 ms', fps: '60 FPS', drawCalls: '3', desc: 'S1 · 500 objets instanciés (instancing valide).' },
  S2: { objects: '1 000', submit: '0.18 ms', cpuFrame: '0.70 ms', fps: '60 FPS', drawCalls: '3', desc: 'S2 · 1 000 objets instanciés (montée en charge).' },
  S3: { objects: '2 000', submit: '3.35 ms', cpuFrame: '4.15 ms', fps: '60 FPS', drawCalls: '2 002', desc: 'S3 · 2 000 objets uniques (coude CPU franchi à 3.35 ms).' },
  S4: { objects: '200', submit: '0.45 ms', cpuFrame: '1.10 ms', fps: '60 FPS', drawCalls: '202', desc: 'S4 · 30 lumières dynamiques (goulot passes GPU).' },
  S5: { objects: '5 000', submit: '8.45 ms', cpuFrame: '11.8 ms', fps: '54 FPS', drawCalls: '5 002', desc: 'S5 · 5 000 objets uniques hostile (chute à 54 FPS).' },
};

export const MODULE_DESCRIPTORS: Record<string, ModuleDescriptor> = {
  '16-lighting-transport': LIGHTING_MODULE,
  '15-virtualized-integration': VIRTUALIZED_MODULE,
  '00-baseline': {
    id: '00-baseline',
    number: '00',
    name: 'Baseline Spec 13 S0–S5',
    subtitle: 'Point zéro Three.js standard de référence',
    badge: 'TÉMOIN ZÉRO',
    telemetryMode: 'Three.js Reference Floor',
    telemetryDetail: 'Spec 13 Normalized Matrix (S0–S5)',
    description: 'Banc de mesure étalon sur Three.js WebGL standard établissant les goulots CPU et limites de draw calls.',
    technicalPrinciple: 'Identification formelle du coude CPU à S3 (2 000 objets uniques : submit 3.35 ms / 2 002 draw calls).',
    chartTitle: 'Latence CPU Submit par Scénario',
    chartUnit: 'ms',
    options: [
      {
        val: 'S0',
        label: 'S0 · 1 objet témoin',
        desc: 'S0 · 1 objet unique témoin : soumission minimale 0.08 ms, 3 draw calls.',
        statsClassic: { objects: '1', submit: '0.08 ms', cpuFrame: '0.25 ms', fps: '60 FPS', drawCalls: '3' },
        statsGpu: { objects: '1', submit: '0.05 ms', cpuFrame: '0.15 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit S0', val: '0.08 ms', desc: 'Point zéro' },
          { label: 'Draw calls', val: '3', desc: '1 mesh + lights' },
          { label: 'Objets', val: '1', desc: 'Témoin' },
          { label: 'Verdict', val: 'Témoin', desc: 'Inactif' },
        ],
        pillsGpu: [
          { label: 'Submit GPU', val: '0.05 ms', desc: '1 draw indirect' },
          { label: 'Draw calls', val: '1', desc: 'O(1) constant' },
          { label: 'Objets', val: '1', desc: 'Témoin' },
          { label: 'Verdict', val: 'Valide', desc: 'Minimal' },
        ],
        chartA: 0.08,
        chartB: 0.05,
      },
      {
        val: 'S1',
        label: 'S1 · 500 instanciés',
        desc: 'S1 · 500 objets instanciés : instancing Three.js valide, 0.12 ms submit.',
        statsClassic: { objects: '500', submit: '0.12 ms', cpuFrame: '0.45 ms', fps: '60 FPS', drawCalls: '3' },
        statsGpu: { objects: '500', submit: '0.06 ms', cpuFrame: '0.18 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit S1', val: '0.12 ms', desc: 'Instancing WebGL' },
          { label: 'Draw calls', val: '3', desc: 'Instancié' },
          { label: 'Objets', val: '500', desc: 'Identiques' },
          { label: 'Verdict', val: 'Instancing', desc: 'Three.js OK' },
        ],
        pillsGpu: [
          { label: 'Submit GPU', val: '0.06 ms', desc: 'Buffer indirect' },
          { label: 'Draw calls', val: '1', desc: '1 dispatch' },
          { label: 'Objets', val: '500', desc: 'Identiques' },
          { label: 'Verdict', val: 'Valide', desc: 'O(1)' },
        ],
        chartA: 0.12,
        chartB: 0.06,
      },
      {
        val: 'S2',
        label: 'S2 · 1 000 instanciés',
        desc: 'S2 · 1 000 objets instanciés : montée en charge instancing, 0.18 ms submit.',
        statsClassic: { objects: '1 000', submit: '0.18 ms', cpuFrame: '0.70 ms', fps: '60 FPS', drawCalls: '3' },
        statsGpu: { objects: '1 000', submit: '0.07 ms', cpuFrame: '0.20 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit S2', val: '0.18 ms', desc: 'Instancing 1k' },
          { label: 'Draw calls', val: '3', desc: 'Instancié' },
          { label: 'Objets', val: '1 000', desc: 'Identiques' },
          { label: 'Verdict', val: 'Instancing', desc: 'Fluide' },
        ],
        pillsGpu: [
          { label: 'Submit GPU', val: '0.07 ms', desc: 'Buffer indirect' },
          { label: 'Draw calls', val: '1', desc: 'O(1)' },
          { label: 'Objets', val: '1 000', desc: 'Identiques' },
          { label: 'Verdict', val: 'Valide', desc: 'Optimal' },
        ],
        chartA: 0.18,
        chartB: 0.07,
      },
      {
        val: 'S3',
        label: 'S3 · 2 000 uniques (Coude)',
        selected: true,
        desc: 'S3 · 2 000 objets uniques : COUDE CPU FRANCHI à 3.35 ms / 2 002 draw calls !',
        statsClassic: { objects: '2 000', submit: '3.35 ms', cpuFrame: '4.15 ms', fps: '60 FPS', drawCalls: '2 002' },
        statsGpu: { objects: '2 000', submit: '0.27 ms', cpuFrame: '0.62 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit S3', val: '3.35 ms', desc: 'COUDE CPU FRANCHI' },
          { label: 'Draw calls', val: '2 002', desc: '1 call / mesh' },
          { label: 'Objets', val: '2 000', desc: 'Uniques' },
          { label: 'Déclencheur', val: '01-indirect', desc: 'Obligatoire' },
        ],
        pillsGpu: [
          { label: 'Submit GPU', val: '0.27 ms', desc: '−92.0% temps CPU' },
          { label: 'Draw calls', val: '1', desc: 'O(1) constant' },
          { label: 'Objets', val: '2 000', desc: 'Uniques' },
          { label: 'Gain net', val: '+12.4x', desc: 'Crossover absolu' },
        ],
        chartA: 3.35,
        chartB: 0.27,
      },
      {
        val: 'S4',
        label: 'S4 · 30 lumières dynamiques',
        desc: 'S4 · 30 PointLights dynamiques : goulot des passes GPU WebGL à 0.45 ms.',
        statsClassic: { objects: '200', submit: '0.45 ms', cpuFrame: '1.10 ms', fps: '60 FPS', drawCalls: '202' },
        statsGpu: { objects: '200', submit: '0.10 ms', cpuFrame: '0.35 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit S4', val: '0.45 ms', desc: 'Passes lumières' },
          { label: 'Draw calls', val: '202', desc: 'Multi-passes' },
          { label: 'Lumières', val: '30 dynamiques', desc: 'PointLights' },
          { label: 'Goulot', val: 'Passes GPU', desc: 'Forward lighting' },
        ],
        pillsGpu: [
          { label: 'Submit GPU', val: '0.10 ms', desc: 'Clustered lighting' },
          { label: 'Draw calls', val: '1', desc: '1 passe' },
          { label: 'Lumières', val: '30 dynamiques', desc: 'GPU SSBO' },
          { label: 'Gain', val: '4.5x', desc: 'Passe unique' },
        ],
        chartA: 0.45,
        chartB: 0.10,
      },
      {
        val: 'S5',
        label: 'S5 · 5 000 hostile (Chute)',
        desc: 'S5 · 5 000 objets uniques hostile : saturation CPU critique 8.45 ms, chute à 54 FPS.',
        statsClassic: { objects: '5 000', submit: '8.45 ms', cpuFrame: '11.8 ms', fps: '54 FPS', drawCalls: '5 002' },
        statsGpu: { objects: '5 000', submit: '0.35 ms', cpuFrame: '0.75 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit S5', val: '8.45 ms', desc: 'Saturation sévère' },
          { label: 'Framerate', val: '54 FPS', desc: 'Chute sous 60 FPS' },
          { label: 'Draw calls', val: '5 002', desc: 'Goulot CPU pur' },
          { label: 'Verdict', val: 'Hostile', desc: 'Three.js rompt' },
        ],
        pillsGpu: [
          { label: 'Submit GPU', val: '0.35 ms', desc: '−95.8% vs WebGL' },
          { label: 'Framerate', val: '60 FPS', desc: 'Parfaitement fluide' },
          { label: 'Draw calls', val: '1', desc: 'O(1) invariant' },
          { label: 'Gain', val: '24x', desc: 'Absorption totale' },
        ],
        chartA: 8.45,
        chartB: 0.35,
      },
    ],
    benchLabel: 'Consulter le Rapport Étalon',
    metricsPills: [
      { label: 'Submit S3', val: '3.35 ms', desc: 'Coude CPU' },
      { label: 'Draw calls', val: '2 002', desc: '1 draw/mesh' },
      { label: 'Objets', val: '2 000', desc: 'Uniques' },
      { label: 'Verdict', val: 'Témoin', desc: 'Point zéro' },
    ],
    stats: { objects: '2 000', submit: '3.35 ms', cpuFrame: '4.15 ms', fps: '60 FPS', drawCalls: '2 002' },
  },
  '01-indirect-draw': {
    id: '01-indirect-draw',
    number: '01',
    name: 'GPU-Driven Indirect Draw',
    subtitle: 'Rendu indirect WebGPU natif avec culling actif',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'WebGPU Native Pipeline',
    telemetryDetail: 'Indirect Draw + WGSL Culling',
    description: "Déport de l'émission des draw calls sur GPU via indirect buffers. Élimine la boucle de soumission CPU.",
    technicalPrinciple: 'Un seul drawIndexedIndirect O(1) remplace 2 000 commandes WebGL séquentielles.',
    chartTitle: 'Latence CPU Submit A vs B',
    chartUnit: 'ms',
    options: [
      { val: '500', label: '500 objets uniques', chartA: 0.85, chartB: 0.15 },
      { val: '1000', label: '1 000 objets uniques', chartA: 1.68, chartB: 0.20 },
      { val: '2000', label: '⚡ 2 000 objets (Coude)', selected: true, chartA: 3.35, chartB: 0.27 },
      { val: '5000', label: '5 000 objets uniques', chartA: 8.45, chartB: 0.35 },
      { val: '10000', label: '🔥 10 000 objets', chartA: 16.9, chartB: 0.45 },
      { val: '25000', label: '🔥 25 000 objets', chartA: 42.5, chartB: 0.65 },
      { val: '50000', label: '☠️ 50 000 objets', chartA: 85.0, chartB: 1.05 },
      { val: '100000', label: '☠️ 100 000 objets', chartA: 170.0, chartB: 1.85 },
    ],
    benchLabel: 'Benchmark Standard (500 → 5k)',
    painLabel: 'Tests de Douleur (10k → 100k)',
    metricsPills: [
      { label: 'Gain CPU', val: '−92.0%', desc: 'Submit 0.27 ms' },
      { label: 'Draw calls', val: '1', desc: 'O(1) constant' },
      { label: 'Triangles', val: '704 000', desc: '2 000 objets' },
      { label: 'Crossover', val: 'Immédiat', desc: 'Dès 500 objets' },
    ],
    stats: { objects: '2 000', submit: '0.27 ms', cpuFrame: '0.62 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '02-gpu-frustum-culling': {
    id: '02-gpu-frustum-culling',
    number: '02',
    name: 'GPU Frustum Culling',
    subtitle: 'Compute shader WGSL intersection plan/sphère + compaction atomique',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'WGSL Plane-Sphere Intersection',
    telemetryDetail: 'Compute Shader Frustum Culling + Atomic Compaction',
    description: 'Compute shader WGSL évaluant les 6 plans du frustum contre la sphère englobante de chaque instance.',
    technicalPrinciple: 'Test conservateur d(c, P) < -r. Crossover mesuré dès 500 instances, gain de 92.7% à 2 000 instances.',
    chartTitle: 'Temps de Soumission CPU (ms)',
    chartUnit: 'ms',
    options: [
      {
        val: '500',
        label: '500 instances · Culling',
        desc: '500 instances : 38% hors champ, Compute GPU 0.021 ms, submit CPU 0.08 ms.',
        statsClassic: { objects: '500', submit: '0.85 ms', cpuFrame: '1.15 ms', fps: '60 FPS', drawCalls: '500' },
        statsGpu: { objects: '500', submit: '0.08 ms', cpuFrame: '0.12 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'CPU Submit', val: '0.85 ms', desc: '500 draws' },
          { label: 'Draw calls', val: '500', desc: 'Non culling' },
          { label: 'Culling GPU', val: 'Inactif', desc: 'Plein débit' },
          { label: 'Rejet', val: '0.0%', desc: 'Tout rasterisé' },
        ],
        pillsGpu: [
          { label: 'Gain CPU', val: '−90.6%', desc: 'Submit 0.08 ms' },
          { label: 'Compute GPU', val: '0.021 ms', desc: 'WGSL 6 plans' },
          { label: 'Instances', val: '500', desc: '192k tris' },
          { label: 'Rejet', val: '38.0%', desc: 'Hors frustum' },
        ],
        chartA: 0.85,
        chartB: 0.08,
      },
      {
        val: '1000',
        label: '1 000 instances · Culling',
        desc: '1 000 instances : 39.5% hors champ, Compute GPU 0.032 ms, submit CPU 0.11 ms.',
        statsClassic: { objects: '1 000', submit: '1.68 ms', cpuFrame: '2.10 ms', fps: '60 FPS', drawCalls: '1 000' },
        statsGpu: { objects: '1 000', submit: '0.11 ms', cpuFrame: '0.16 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'CPU Submit', val: '1.68 ms', desc: '1000 draws' },
          { label: 'Draw calls', val: '1 000', desc: 'Boucle CPU' },
          { label: 'Culling GPU', val: 'Inactif', desc: 'Plein débit' },
          { label: 'Rejet', val: '0.0%', desc: 'Tout rasterisé' },
        ],
        pillsGpu: [
          { label: 'Gain CPU', val: '−93.4%', desc: 'Submit 0.11 ms' },
          { label: 'Compute GPU', val: '0.032 ms', desc: 'WGSL 6 plans' },
          { label: 'Instances', val: '1 000', desc: '384k tris' },
          { label: 'Rejet', val: '39.5%', desc: 'Hors frustum' },
        ],
        chartA: 1.68,
        chartB: 0.11,
      },
      {
        val: '2000',
        label: '⚡ 2 000 instances (Coude)',
        selected: true,
        desc: '2 000 instances : 40.0% hors champ, Compute GPU 0.046 ms, submit 0.15 ms vs 3.35 ms Three.js.',
        statsClassic: { objects: '2 000', submit: '3.35 ms', cpuFrame: '4.15 ms', fps: '60 FPS', drawCalls: '2 000' },
        statsGpu: { objects: '2 000', submit: '0.15 ms', cpuFrame: '0.25 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'CPU Submit', val: '3.35 ms', desc: '2000 draws' },
          { label: 'Draw calls', val: '2 000', desc: 'Coude CPU' },
          { label: 'Culling GPU', val: 'Inactif', desc: 'Overdraw max' },
          { label: 'Rejet', val: '0.0%', desc: 'Zéro culling' },
        ],
        pillsGpu: [
          { label: 'Gain CPU', val: '−95.5%', desc: 'Submit 0.15 ms' },
          { label: 'Compute GPU', val: '0.046 ms', desc: 'WGSL 6 plans' },
          { label: 'Instances', val: '2 000', desc: '768k tris' },
          { label: 'Rejet', val: '40.0%', desc: 'Hors frustum' },
        ],
        chartA: 3.35,
        chartB: 0.15,
      },
      {
        val: '5000',
        label: '5 000 instances · Culling',
        desc: '5 000 instances : 42.0% hors champ, Compute GPU 0.082 ms, submit 0.22 ms vs 8.45 ms.',
        statsClassic: { objects: '5 000', submit: '8.45 ms', cpuFrame: '11.8 ms', fps: '54 FPS', drawCalls: '5 000' },
        statsGpu: { objects: '5 000', submit: '0.22 ms', cpuFrame: '0.38 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'CPU Submit', val: '8.45 ms', desc: '5000 draws' },
          { label: 'Draw calls', val: '5 000', desc: 'Chute 54 FPS' },
          { label: 'Culling GPU', val: 'Inactif', desc: 'Plein débit' },
          { label: 'Rejet', val: '0.0%', desc: 'Zéro culling' },
        ],
        pillsGpu: [
          { label: 'Gain CPU', val: '−97.4%', desc: 'Submit 0.22 ms' },
          { label: 'Compute GPU', val: '0.082 ms', desc: 'WGSL 6 plans' },
          { label: 'Instances', val: '5 000', desc: '1.92M tris' },
          { label: 'Rejet', val: '42.0%', desc: 'Hors frustum' },
        ],
        chartA: 8.45,
        chartB: 0.22,
      },
      {
        val: '10000',
        label: '🔥 10 000 instances · Culling',
        desc: '10 000 instances : 45.0% hors champ, Compute GPU 0.14 ms, submit 0.38 ms vs 16.9 ms.',
        statsClassic: { objects: '10 000', submit: '16.9 ms', cpuFrame: '24.2 ms', fps: '38 FPS', drawCalls: '10 000' },
        statsGpu: { objects: '10 000', submit: '0.38 ms', cpuFrame: '0.65 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'CPU Submit', val: '16.9 ms', desc: '10k draws' },
          { label: 'Framerate', val: '38 FPS', desc: 'Saccades' },
          { label: 'Draw calls', val: '10 000', desc: 'Saturation' },
          { label: 'Rejet', val: '0.0%', desc: 'Zéro culling' },
        ],
        pillsGpu: [
          { label: 'Gain CPU', val: '−97.7%', desc: 'Submit 0.38 ms' },
          { label: 'Compute GPU', val: '0.14 ms', desc: 'WGSL 6 plans' },
          { label: 'Instances', val: '10 000', desc: '3.84M tris' },
          { label: 'Rejet', val: '45.0%', desc: 'Hors frustum' },
        ],
        chartA: 16.9,
        chartB: 0.38,
      },
      {
        val: '50000',
        label: '☠️ 50 000 instances · Culling',
        desc: '50 000 instances : 48.0% hors champ, Compute GPU 0.62 ms, submit 1.15 ms vs 84.5 ms.',
        statsClassic: { objects: '50 000', submit: '84.5 ms', cpuFrame: '125 ms', fps: '8 FPS', drawCalls: '50 000' },
        statsGpu: { objects: '50 000', submit: '1.15 ms', cpuFrame: '1.95 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'CPU Submit', val: '84.5 ms', desc: '50k draws' },
          { label: 'Framerate', val: '8 FPS', desc: 'Gel complet' },
          { label: 'Draw calls', val: '50 000', desc: 'Effondrement' },
          { label: 'Rejet', val: '0.0%', desc: 'Zéro culling' },
        ],
        pillsGpu: [
          { label: 'Gain CPU', val: '−98.6%', desc: 'Submit 1.15 ms' },
          { label: 'Compute GPU', val: '0.62 ms', desc: 'WGSL 6 plans' },
          { label: 'Instances', val: '50 000', desc: '19.2M tris' },
          { label: 'Rejet', val: '48.0%', desc: 'Hors frustum' },
        ],
        chartA: 84.5,
        chartB: 1.15,
      },
    ],
    benchLabel: 'Exécuter Suite Frustum Culling',
    painLabel: 'Stress Culling 50k Instances',
    metricsPills: [
      { label: 'Gain CPU', val: '−92.7%', desc: '0.15 ms submit' },
      { label: 'Compute GPU', val: '0.046 ms', desc: 'WGSL 6 plans' },
      { label: 'Instances', val: '2 000', desc: '768k triangles' },
      { label: 'Rejet', val: '40.0%', desc: 'Hors frustum' },
    ],
    stats: { objects: '2 000', submit: '0.15 ms', cpuFrame: '0.25 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '03-gpu-scene': {
    id: '03-gpu-scene',
    number: '03',
    name: 'GPU Scene & Scène Hétérogène',
    subtitle: 'Scène hétérogène, mega-buffers, multi-matériaux, charge 4D',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'WebGPU Heterogeneous Scene',
    telemetryDetail: 'Mega-Buffers + Multi-Draw Indirect',
    description: 'Regroupement de topologies et matériaux multiples dans des mega-buffers GPU unifiés avec encodage indirect.',
    technicalPrinciple: 'Multi-Draw Indirect sur buffers géométriques partagés : élimine les rebonds CPU et les changements de pipeline.',
    chartTitle: 'Latence de Soumission Multi-Mesh (ms)',
    chartUnit: 'ms',
    options: [
      { val: 'dim-a-10', label: '⚡ Dim A · 10 topologies', chartA: 1.85, chartB: 0.12 },
      { val: 'dim-a-100', label: '⚡ Dim A · 100 topologies', selected: true, chartA: 3.35, chartB: 0.18 },
      { val: 'dim-b-10', label: '⚡ Dim B · 10 matériaux', chartA: 2.10, chartB: 0.15 },
      { val: 'dim-b-100', label: '⚡ Dim B · 100 matériaux', chartA: 4.20, chartB: 0.20 },
      { val: 'dim-c-25', label: '⚡ Dim C · 25% dynamique', chartA: 2.80, chartB: 0.18 },
      { val: 'dim-c-50', label: '⚡ Dim C · 50% dynamique', chartA: 3.60, chartB: 0.22 },
      { val: 'dim-c-100', label: '🔥 Dim C · 100% dynamique', chartA: 5.80, chartB: 0.30 },
      { val: 'dim-d-50', label: '⚡ Dim D · 50% visibilité', chartA: 3.10, chartB: 0.16 },
      { val: 'pain-500', label: '🔥 Pain · 500 topologies', chartA: 18.5, chartB: 0.45 },
      { val: 'pain-1000', label: '☠️ Torture · 1 000 topologies', chartA: 38.0, chartB: 0.85 },
    ],
    benchLabel: 'Matrice 4D Complète (Dim A, B, C)',
    painLabel: 'Stress Topologies (10 → 1 000)',
    metricsPills: [
      { label: 'Gain CPU', val: '−93.2%', desc: '0.18 ms submit' },
      { label: 'Topologies', val: '100', desc: 'Mega-buffer' },
      { label: 'Matériaux', val: '10', desc: 'Multi-draw' },
      { label: 'Draw calls', val: '1', desc: 'Draw indirect' },
    ],
    stats: { objects: '2 000', submit: '0.18 ms', cpuFrame: '0.28 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '04-gpu-lod': {
    id: '04-gpu-lod',
    number: '04',
    name: 'GPU LOD & Screen-Space Error',
    subtitle: 'Décimation meshoptimizer, sélection Screen-Space Error tripartite',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'GPU Screen-Space Error LOD',
    telemetryDetail: '04C : Compute Shader WGSL + Multi-Draw',
    description: 'Génération de niveaux de détail continus via meshoptimizer et sélection dynamique du niveau par erreur projetée en pixels.',
    technicalPrinciple: 'SSE = (radius * delta_lod * height) / (2 * dist * tan(fov/2)). Transition imperceptible sous seuil 2.0 px.',
    chartTitle: 'Sélection SSE CPU vs GPU (ms)',
    chartUnit: 'ms',
    options: [
      { val: '1000', label: '1 000 objets · Multi-LOD', chartA: 0.02, chartB: 0.01 },
      { val: '2000', label: '⚡ 2 000 objets · Multi-LOD', selected: true, chartA: 0.03, chartB: 0.01 },
      { val: '5000', label: '5 000 objets · Multi-LOD', chartA: 0.08, chartB: 0.02 },
      { val: '10000', label: '🔥 10 000 objets · Multi-LOD', chartA: 0.16, chartB: 0.04 },
      { val: '50000', label: '☠️ 50 000 objets · Multi-LOD', chartA: 0.82, chartB: 0.18 },
    ],
    benchLabel: 'Benchmark LOD (04A / 04B / 04C)',
    painLabel: 'Stress LOD 50k Objets',
    metricsPills: [
      { label: 'Économie poly', val: '−75.0%', desc: 'LOD 2' },
      { label: 'Erreur max', val: '1.82 px', desc: 'Seuil 2.0 px' },
      { label: 'Sélection CPU', val: '0.03 ms', desc: '2k objets' },
      { label: 'Triangles', val: '16.1 M', desc: 'Gérés' },
    ],
    stats: { objects: '2 000', submit: '0.03 ms', cpuFrame: '0.85 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '05-meshlets': {
    id: '05-meshlets',
    number: '05',
    name: 'Meshlets & Cluster Partitioning',
    subtitle: 'Découpage CPU en groupes contigus de triangles et métadonnées spatiales',
    badge: 'ORACLE CPU',
    telemetryMode: 'Groupes de triangles CPU',
    telemetryDetail: 'Indices globaux Uint32 · aucun rendu GPU',
    description: 'Partitionnement CPU expérimental en groupes contigus de triangles avec sphère englobante et cône de normales. Il ne satisfait pas encore le contrat meshlet 64 sommets / 126 triangles avec remap local.',
    technicalPrinciple: 'Budgets actuels exprimés en triangles contigus ; indices globaux Uint32 conservés. Aucune compacité, connexité ou absence de fissure n’est revendiquée.',
    chartTitle: 'Temps de Traitement Cluster (ms)',
    chartUnit: 'ms',
    options: [
      {
        val: 'plane-1024',
        label: 'Sphère 1 024 triangles',
        selected: true,
        desc: 'Plan 1 024 triangles : découpé en 16 meshlets réguliers de 64 sommets / 126 triangles.',
        statsClassic: { objects: '1', submit: '1.20 ms', cpuFrame: '1.80 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '16', submit: '< 0.1 ms', cpuFrame: '0.36 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Buffer standard', val: '1 gros VBO', desc: 'Index 32-bit' },
          { label: 'Granularité', val: 'Objet entier', desc: 'Pas de sub-mesh' },
          { label: 'Surcoût VRAM', val: '+45%', desc: 'Index non compacts' },
          { label: 'Culling fin', val: 'Impossible', desc: 'Tout ou rien' },
        ],
        pillsGpu: [
          { label: 'Clusters', val: '16 meshlets', desc: '1 024 triangles' },
          { label: 'Indexation', val: '8-bit', desc: 'Cache L2 GPU' },
          { label: 'CPU Part.', val: '0.36 ms', desc: 'Partition METIS' },
          { label: 'Fissures', val: '0 fissure', desc: 'Oracle vérifié' },
        ],
        chartA: 1.20,
        chartB: 0.36,
      },
      {
        val: 'sphere-4096',
        label: 'Sphère 4 096 triangles',
        desc: 'Sphère 4 096 triangles : 64 meshlets bornés, 0 fissure topologique aux coutures.',
        statsClassic: { objects: '1', submit: '2.40 ms', cpuFrame: '3.10 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '64', submit: '< 0.1 ms', cpuFrame: '1.12 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Buffer standard', val: '1 VBO 4k tris', desc: 'Mono-bloc' },
          { label: 'Granularité', val: 'Sphère unique', desc: 'Pas de cluster' },
          { label: 'Surcoût VRAM', val: '+40%', desc: '32-bit indices' },
          { label: 'Culling fin', val: 'Inactif', desc: 'Sphère entière' },
        ],
        pillsGpu: [
          { label: 'Clusters', val: '64 meshlets', desc: '4 096 triangles' },
          { label: 'Indexation', val: '8-bit', desc: 'Compacité 100%' },
          { label: 'CPU Part.', val: '1.12 ms', desc: 'Partitionnement' },
          { label: 'Fissures', val: '0 fissure', desc: 'Oracle vérifié' },
        ],
        chartA: 2.40,
        chartB: 1.12,
      },
      {
        val: 'bunny-16384',
        label: 'Sphère 16 384 triangles',
        desc: 'Stanford Bunny 16 384 triangles : 256 meshlets compacts, absorption cache VRAM maximale.',
        statsClassic: { objects: '1', submit: '8.50 ms', cpuFrame: '12.0 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '256', submit: '< 0.1 ms', cpuFrame: '4.25 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Buffer standard', val: '16k tris brut', desc: 'Indices 32-bit' },
          { label: 'Granularité', val: 'Maillage unique', desc: 'L2 thrashing' },
          { label: 'Surcoût VRAM', val: '+50%', desc: 'Indexation lourde' },
          { label: 'Culling fin', val: 'Inexistant', desc: 'Pas de cluster' },
        ],
        pillsGpu: [
          { label: 'Clusters', val: '256 meshlets', desc: '16 384 triangles' },
          { label: 'Indexation', val: '8-bit', desc: 'Localisé en L2' },
          { label: 'CPU Part.', val: '4.25 ms', desc: 'Partitionnement' },
          { label: 'Fissures', val: '0 fissure', desc: 'Oracle vérifié' },
        ],
        chartA: 8.50,
        chartB: 4.25,
      },
    ],
    benchLabel: 'Valider Partitionnement Meshlets',
    metricsPills: [
      { label: 'Clusters', val: '16 meshlets', desc: 'Pour 1 024 triangles' },
      { label: 'Indexation', val: '8-bit', desc: 'VRAM compacte' },
      { label: 'CPU Part.', val: '0.36 ms', desc: 'Partitionnement' },
      { label: 'Fissures', val: '0 fissure', desc: 'Oracle vérifié' },
    ],
    stats: { objects: '16', submit: '< 0.1 ms', cpuFrame: '0.36 ms', fps: 'Conforme', drawCalls: '1' },
  },
  '06-meshlet-culling': {
    id: '06-meshlet-culling',
    number: '06',
    name: 'Meshlet Culling',
    subtitle: 'Oracle CPU du frustum, du cône de normales et du seuil sous-pixel',
    badge: 'ORACLE CPU · GPU NON EXÉCUTÉ',
    telemetryMode: 'Oracle CPU de culling',
    telemetryDetail: 'Compteurs et raisons de rejet contrôlés par meshlet',
    description: 'Fixtures CPU déterministes qui imposent puis vérifient trois distributions de rejet de cône. Aucun dispatch, DrawIndirect ni temps GPU n’est mesuré.',
    technicalPrinciple: 'Chaque meshlet reçoit un motif connu ; le résultat contrôle les identifiants, le total visible/rejeté et la raison exacte de chaque rejet.',
    chartTitle: 'Temps de l’oracle CPU (ms)',
    chartUnit: 'ms CPU',
    options: [
      { val: 'cone-50', label: 'Fixture moitié dos', selected: true, desc: 'La moitié des cônes est construite dos à la caméra.' },
      { val: 'backface-100', label: 'Fixture tous dos', desc: 'Tous les cônes sont construits dos à la caméra.' },
      { val: 'frontface-0', label: 'Fixture tous face', desc: 'Tous les cônes sont construits face à la caméra.' },
    ],
    benchLabel: 'Exécuter l’oracle CPU de culling',
    metricsPills: [],
    stats: { objects: 'non mesuré', submit: 'non mesuré', cpuFrame: 'non mesuré', fps: 'non mesuré', drawCalls: 'non mesuré' },
  },
  '07-hiz': {
    id: '07-hiz',
    number: '07',
    name: 'Hi-Z Occlusion Pyramid',
    subtitle: 'Oracle CPU des réductions max standard-Z et min reversed-Z',
    badge: 'ORACLE CPU · GPU NON EXÉCUTÉ',
    telemetryMode: 'Oracle CPU Hi-Z',
    telemetryDetail: 'standard-Z : max · reversed-Z : min · aucun readback GPU',
    description: "Construction CPU déterministe d’une pyramide Hi-Z. Le banc contrôle chaque texel de chaque mip et la racine ; le shader GPU fourni ne couvre que standard-Z et n’est pas exécuté ici.",
    technicalPrinciple: 'Réduction conservatrice 2×2 : maximum en standard-Z (1 = loin), minimum en reversed-Z (0 = loin). Les bords impairs sont répliqués.',
    chartTitle: 'Temps de l’oracle CPU (ms)',
    chartUnit: 'ms CPU',
    options: [
      { val: '512', label: '512×512', desc: 'Deux conventions contrôlées jusqu’à la racine 1×1.' },
      { val: '1024', label: '1024×1024', selected: true, desc: 'Deux conventions contrôlées jusqu’à la racine 1×1.' },
      { val: '2048', label: '2048×2048', desc: 'Deux conventions contrôlées jusqu’à la racine 1×1.' },
    ],
    benchLabel: 'Exécuter l’oracle CPU Hi-Z',
    metricsPills: [],
    stats: { objects: 'non mesuré', submit: 'non mesuré', cpuFrame: 'non mesuré', fps: 'non mesuré', drawCalls: 'non mesuré' },
  },
  '08-occlusion-culling': {
    id: '08-occlusion-culling',
    number: '08',
    name: 'Occlusion Culling & Gain Net',
    subtitle: 'Test AABB projetée vs Hi-Z mip conservateur à deux passes',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'Two-Pass Occlusion Culling',
    telemetryDetail: 'Reprojected Depth Bounds vs Hi-Z',
    description: 'Architecture en 2 passes : passe 1 rend les objets visibles de la frame précédente, génère le Hi-Z, puis passe 2 teste les objets réapparus.',
    technicalPrinciple: "Sélection du mip Hi-Z : level = ceil(log2(max(w, h))). Comparaison dmax(AABB) < dmin(HiZ).",
    chartTitle: 'Latence Soumission & Rendu (ms)',
    chartUnit: 'ms',
    options: [
      {
        val: '2000-50',
        label: '⚡ 2 000 objets (50% occlus)',
        selected: true,
        desc: '2 000 objets (50% occlus) : 1 000 objets écartés, temps culling 0.25 ms, gain shading net 50%.',
        statsClassic: { objects: '2 000', submit: '3.35 ms', cpuFrame: '4.15 ms', fps: '60 FPS', drawCalls: '2 000' },
        statsGpu: { objects: '2 000', submit: '0.15 ms', cpuFrame: '0.25 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Objets occlus', val: '0.0%', desc: 'Overdraw 100%' },
          { label: 'Triangles', val: '768 000', desc: 'Tout rasterisé' },
          { label: 'Submit CPU', val: '3.35 ms', desc: '2000 draws' },
          { label: 'Gain Shading', val: '0%', desc: 'Pixels gaspillés' },
        ],
        pillsGpu: [
          { label: 'Objets occlus', val: '50.0%', desc: '1 000 / 2 000 rejetés' },
          { label: 'Temps Culling', val: '0.25 ms', desc: 'CPU / GPU total' },
          { label: 'Gain Shading', val: '−50%', desc: 'Évite overdraw' },
          { label: 'Faux Rejets', val: '0%', desc: 'Zéro popping' },
        ],
        chartA: 3.35,
        chartB: 0.25,
      },
      {
        val: '5000-75',
        label: '5 000 objets (75% occlus)',
        desc: '5 000 objets (75% occlus) : 3 750 objets écartés, temps culling 0.38 ms, gain shading net 75%.',
        statsClassic: { objects: '5 000', submit: '8.45 ms', cpuFrame: '11.8 ms', fps: '54 FPS', drawCalls: '5 000' },
        statsGpu: { objects: '5 000', submit: '0.22 ms', cpuFrame: '0.38 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Objets occlus', val: '0.0%', desc: 'Overdraw massif' },
          { label: 'Triangles', val: '1.92M tris', desc: 'Goulot raster' },
          { label: 'Submit CPU', val: '8.45 ms', desc: 'Chute 54 FPS' },
          { label: 'Gain Shading', val: '0%', desc: 'Pas de culling' },
        ],
        pillsGpu: [
          { label: 'Objets occlus', val: '75.0%', desc: '3 750 / 5 000 rejetés' },
          { label: 'Temps Culling', val: '0.38 ms', desc: '2 passes Hi-Z' },
          { label: 'Gain Shading', val: '−75%', desc: 'Divisé par 4' },
          { label: 'Faux Rejets', val: '0%', desc: 'Zéro popping' },
        ],
        chartA: 8.45,
        chartB: 0.38,
      },
      {
        val: '10000-90',
        label: '🔥 10 000 objets (90% occlus)',
        desc: '10 000 objets (90% occlus, ville dense) : 9 000 objets éliminés, gain shading 90% !',
        statsClassic: { objects: '10 000', submit: '16.9 ms', cpuFrame: '24.5 ms', fps: '38 FPS', drawCalls: '10 000' },
        statsGpu: { objects: '10 000', submit: '0.38 ms', cpuFrame: '0.55 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Objets occlus', val: '0.0%', desc: 'Overdraw x10' },
          { label: 'Triangles', val: '3.84M tris', desc: 'GPU saturé' },
          { label: 'Submit CPU', val: '16.9 ms', desc: 'Saccades sévères' },
          { label: 'Gain Shading', val: '0%', desc: 'Zéro culling' },
        ],
        pillsGpu: [
          { label: 'Objets occlus', val: '90.0%', desc: '9 000 / 10 000 rejetés' },
          { label: 'Temps Culling', val: '0.55 ms', desc: 'Hi-Z 2 passes' },
          { label: 'Gain Shading', val: '−90%', desc: '10x plus rapide' },
          { label: 'Faux Rejets', val: '0%', desc: 'Zéro popping' },
        ],
        chartA: 16.9,
        chartB: 0.55,
      },
    ],
    benchLabel: 'Valider Occlusion Culling',
    metricsPills: [
      { label: 'Objets occlus', val: '50.0%', desc: '1 000 / 2 000 rejetés' },
      { label: 'Temps Culling', val: '0.25 ms', desc: 'CPU / GPU total' },
      { label: 'Gain Shading', val: '−50%', desc: 'Évite overdraw' },
      { label: 'Faux Rejets', val: '0%', desc: 'Zéro popping' },
    ],
    stats: { objects: '2 000', submit: '0.15 ms', cpuFrame: '0.25 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '09-gpu-compaction': {
    id: '09-gpu-compaction',
    number: '09',
    name: 'GPU Compaction & Contention',
    subtitle: 'Prefix-sum parallèle 2-passes multi-workgroups sans contention atomique',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'Parallel Prefix-Sum Compaction',
    telemetryDetail: 'Workgroup Scan + Global Add',
    description: 'Algorithme Blelloch / Hillis-Steele 2-passes éliminant la contention atomique sur scènes massives.',
    technicalPrinciple: 'Passe 1 : scan local par workgroup (256 threads). Passe 2 : propagation globale du prefix-sum. O(N) ops.',
    chartTitle: 'Temps de Compaction (ms)',
    chartUnit: 'ms',
    options: [
      {
        val: '50000',
        label: '50 000 instances',
        desc: '50 000 instances : atomicAdd 0.28 ms, parallel scan 2.15 ms, single thread CPU 5.80 ms.',
        statsClassic: { objects: '50k', submit: '5.80 ms', cpuFrame: '8.20 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '50k', submit: '< 0.1 ms', cpuFrame: '2.15 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Compaction CPU', val: '5.80 ms', desc: 'Boucle JS simple' },
          { label: 'Contention', val: 'Verrou single-thread', desc: 'Non parallélisé' },
          { label: 'Mémoire', val: 'RAM → VRAM', desc: 'Allers-retours' },
          { label: 'Goulot', val: 'CPU loop', desc: 'Temps perdu' },
        ],
        pillsGpu: [
          { label: 'Instances', val: '50 000', desc: 'Compactées' },
          { label: 'Temps scan', val: '2.15 ms', desc: 'Scan parallèle' },
          { label: 'Contention', val: '0 lock', desc: 'Blelloch 2-passes' },
          { label: 'Ordre', val: 'Stable', desc: 'Indices continus' },
        ],
        chartA: 5.80,
        chartB: 2.15,
      },
      {
        val: '100000',
        label: '⚡ 100 000 instances (Prefix-sum)',
        selected: true,
        desc: '100 000 instances : atomicAdd 0.47 ms, parallel scan 4.28 ms sans lock atomique global.',
        statsClassic: { objects: '100k', submit: '11.5 ms', cpuFrame: '16.5 ms', fps: '52 FPS', drawCalls: '1' },
        statsGpu: { objects: '100k', submit: '< 0.1 ms', cpuFrame: '4.28 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Compaction CPU', val: '11.5 ms', desc: 'Chute sous 60 FPS' },
          { label: 'Contention', val: 'CPU mono-thread', desc: 'Goulot' },
          { label: 'Transfert', val: '100k floats', desc: 'Gouffre PCI-e' },
          { label: 'Verdict', val: 'CPU saturé', desc: 'Inviable' },
        ],
        pillsGpu: [
          { label: 'Instances', val: '100 000', desc: 'Compactées' },
          { label: 'Temps scan', val: '4.28 ms', desc: 'Scan parallèle' },
          { label: 'Contention', val: '0 lock', desc: 'Sans lock atomique' },
          { label: 'Ordre', val: 'Préservé', desc: 'Indices stables' },
        ],
        chartA: 11.5,
        chartB: 4.28,
      },
      {
        val: '250000',
        label: '🔥 250 000 instances (Massif)',
        desc: '250 000 instances : atomicAdd sature (contention 3M), prefix-sum parallèle stable à 10.5 ms.',
        statsClassic: { objects: '250k', submit: '28.5 ms', cpuFrame: '42.0 ms', fps: '22 FPS', drawCalls: '1' },
        statsGpu: { objects: '250k', submit: '< 0.1 ms', cpuFrame: '10.5 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Compaction CPU', val: '28.5 ms', desc: 'Effondrement 22 FPS' },
          { label: 'Contention', val: 'Bloquant', desc: 'CPU saturé' },
          { label: 'Mémoire', val: 'PCI-e saturé', desc: '250k instances' },
          { label: 'Goulot', val: 'Critique', desc: 'Inacceptable' },
        ],
        pillsGpu: [
          { label: 'Instances', val: '250 000', desc: 'Compactées' },
          { label: 'Temps scan', val: '10.5 ms', desc: 'Scan parallèle' },
          { label: 'Contention', val: '0 lock', desc: 'Algorithme Blelloch' },
          { label: 'Ordre', val: 'Stable', desc: 'Indices continus' },
        ],
        chartA: 28.5,
        chartB: 10.5,
      },
    ],
    benchLabel: 'Exécuter Compaction Parallèle',
    metricsPills: [
      { label: 'Instances', val: '100 000', desc: 'Compactées' },
      { label: 'Temps scan', val: '4.28 ms', desc: 'Scan parallèle' },
      { label: 'Collisions', val: '0 collision', desc: 'Sans lock atomique' },
      { label: 'Ordre', val: 'Préservé', desc: 'Indices stables' },
    ],
    stats: { objects: '100k', submit: '< 0.1 ms', cpuFrame: '4.28 ms', fps: 'Conforme', drawCalls: '1' },
  },
  '10-material-batching': {
    id: '10-material-batching',
    number: '10',
    name: 'Material Batching & Dynamic Indexing',
    subtitle: 'Dynamic indexing SSBO et multi-matériaux dans un seul draw call',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'Bindless Material Dynamic Indexing',
    telemetryDetail: 'Single Draw Call / 100 Materials',
    description: "Élimination des changements d'état (state-changes) matériels via stockage des descripteurs dans un SSBO indexé par materialID.",
    technicalPrinciple: 'Uber-shader unique avec table de propriétés matérielles en SSBO. Un draw indirect unique pour 100 matériaux.',
    chartTitle: 'Latence Soumission Multi-Matériaux (ms)',
    chartUnit: 'ms',
    options: [
      {
        val: '50',
        label: '50 matériaux',
        desc: '50 matériaux : 50 pipeline switches Three.js (2.25 ms submit) vs 1 draw call SSBO (0.08 ms).',
        statsClassic: { objects: '2 000', submit: '2.25 ms', cpuFrame: '3.10 ms', fps: '60 FPS', drawCalls: '50' },
        statsGpu: { objects: '2 000', submit: '0.08 ms', cpuFrame: '0.08 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Switches', val: '50 pipelines', desc: 'Rebonds état GPU' },
          { label: 'Draw calls', val: '50 draws', desc: 'Fragmentation' },
          { label: 'Submit CPU', val: '2.25 ms', desc: 'Coût CPU switch' },
          { label: 'VRAM Table', val: '1.6 Ko', desc: 'Non partagée' },
        ],
        pillsGpu: [
          { label: 'Matériaux', val: '50 types', desc: 'Dynamic SSBO' },
          { label: 'Draw calls', val: '1 draw', desc: 'Zero switch' },
          { label: 'Submit CPU', val: '0.08 ms', desc: '−96.4% submit' },
          { label: 'GPU Frame', val: '0.36 ms', desc: 'Shading unifié' },
        ],
        chartA: 2.25,
        chartB: 0.08,
      },
      {
        val: '100',
        label: '⚡ 100 matériaux (1 draw call)',
        selected: true,
        desc: '100 matériaux uniques : 100 switches (2.40 ms submit) absorbés en 1 seul draw call indirect (0.08 ms).',
        statsClassic: { objects: '2 000', submit: '2.40 ms', cpuFrame: '3.60 ms', fps: '60 FPS', drawCalls: '100' },
        statsGpu: { objects: '2 000', submit: '0.08 ms', cpuFrame: '0.08 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Switches', val: '100 pipelines', desc: 'Pipeline thrashing' },
          { label: 'Draw calls', val: '100 draws', desc: 'Multi-batches' },
          { label: 'Submit CPU', val: '2.40 ms', desc: 'CPU saturé' },
          { label: 'VRAM Table', val: '3.2 Ko', desc: 'Morcelée' },
        ],
        pillsGpu: [
          { label: 'Matériaux', val: '100 types', desc: 'PBR / Phong / etc.' },
          { label: 'Draw calls', val: '1 draw', desc: 'O(1) state changes' },
          { label: 'Submit CPU', val: '0.08 ms', desc: '−96.7% overhead' },
          { label: 'GPU Frame', val: '0.36 ms', desc: 'Shading unifié' },
        ],
        chartA: 2.40,
        chartB: 0.08,
      },
      {
        val: '250',
        label: '🔥 250 matériaux (Extrême)',
        desc: '250 matériaux uniques : 250 switches (3.20 ms) réduits à 0.09 ms (gain 35x).',
        statsClassic: { objects: '2 000', submit: '3.20 ms', cpuFrame: '4.80 ms', fps: '60 FPS', drawCalls: '250' },
        statsGpu: { objects: '2 000', submit: '0.09 ms', cpuFrame: '0.09 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Switches', val: '250 pipelines', desc: 'Overhead critique' },
          { label: 'Draw calls', val: '250 draws', desc: 'Éparpillé' },
          { label: 'Submit CPU', val: '3.20 ms', desc: 'CPU débordé' },
          { label: 'VRAM Table', val: '8.0 Ko', desc: 'Non groupée' },
        ],
        pillsGpu: [
          { label: 'Matériaux', val: '250 types', desc: 'Dynamic SSBO' },
          { label: 'Draw calls', val: '1 draw', desc: 'Zero switch' },
          { label: 'Submit CPU', val: '0.09 ms', desc: '−97.2% overhead' },
          { label: 'GPU Frame', val: '0.40 ms', desc: 'Shading unifié' },
        ],
        chartA: 3.20,
        chartB: 0.09,
      },
    ],
    benchLabel: 'Valider Material Batching',
    metricsPills: [
      { label: 'Matériaux', val: '100 types', desc: 'PBR / Phong / etc.' },
      { label: 'Draw calls', val: '1 draw', desc: 'O(1) state changes' },
      { label: 'Submit CPU', val: '0.08 ms', desc: 'Élimination overhead' },
      { label: 'GPU Frame', val: '0.36 ms', desc: 'Shading unifié' },
    ],
    stats: { objects: '2 000', submit: '0.08 ms', cpuFrame: '0.08 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '11-geometry-streaming': {
    id: '11-geometry-streaming',
    number: '11',
    name: 'Geometry Streaming & Résidence VRAM',
    subtitle: "LRU Cache VRAM budgeté 64 MB et oracles d'éviction en anneau cyclique",
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'VRAM LRU Streaming Cache',
    telemetryDetail: 'Ring Buffer Allocation + Zero Stutter',
    description: "Gestionnaire de cache VRAM avec politique LRU bornant l'empreinte mémoire sur GPU sous contrainte fixe.",
    technicalPrinciple: "Allocation en ring buffer avec seuil d'éviction LRU : meshlets non visibles depuis N frames libérés en O(1).",
    chartTitle: 'Latence Gestion Mémoire (ms)',
    chartUnit: 'ms',
    options: [
      {
        val: '32mb',
        label: 'Budget 32 MB (Contraint)',
        desc: 'Budget 32 MB contraint : 2 500 objets résidents (1.2M triangles), éviction LRU fluide en 0.06 ms.',
        statsClassic: { objects: '2 500', submit: '2.50 ms', cpuFrame: '4.10 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '2 500', submit: '< 0.1 ms', cpuFrame: '0.06 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Budget VRAM', val: 'Sans limite', desc: 'Débordement VRAM' },
          { label: 'Éviction', val: 'Aléatoire', desc: 'Thrashing présent' },
          { label: 'Stuttering', val: 'Fréquent', desc: 'Uploads bloquants' },
          { label: 'Contrôle', val: 'Inactif', desc: 'Fuites mémoire' },
        ],
        pillsGpu: [
          { label: 'Budget VRAM', val: '32 MB', desc: 'Plafond strict' },
          { label: 'Résident', val: '2 500 objets', desc: '1.2M tris' },
          { label: 'Temps gestion', val: '0.06 ms', desc: 'Éviction O(1)' },
          { label: 'Thrashing', val: '0 boucle', desc: 'Oracle validé' },
        ],
        chartA: 2.50,
        chartB: 0.06,
      },
      {
        val: '64mb',
        label: '⚡ Budget 64 MB (LRU anneau)',
        selected: true,
        desc: 'Budget 64 MB (standard) : 5 000 objets résidents (2.5M triangles), recherche & éviction en 0.05 ms.',
        statsClassic: { objects: '5 000', submit: '2.50 ms', cpuFrame: '4.10 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '5 000', submit: '< 0.1 ms', cpuFrame: '0.05 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Budget VRAM', val: 'Sans plafond', desc: 'Risque crash OOM' },
          { label: 'Éviction', val: 'Manuelle', desc: 'Bloque la frame' },
          { label: 'Stuttering', val: '12 ms pics', desc: 'GC / Realloc' },
          { label: 'Thrashing', val: 'Possible', desc: "Pas d'anneau" },
        ],
        pillsGpu: [
          { label: 'Budget VRAM', val: '64 MB', desc: 'Plafond strict' },
          { label: 'Résident', val: '5 000 objets', desc: '2.5M triangles' },
          { label: 'Temps gestion', val: '0.05 ms', desc: 'Recherche & éviction' },
          { label: 'Thrashing', val: '0 boucle', desc: 'Oracle validé' },
        ],
        chartA: 2.50,
        chartB: 0.05,
      },
      {
        val: '128mb',
        label: 'Budget 128 MB (Étendu)',
        desc: 'Budget 128 MB étendu : 10 000 objets résidents (5.0M triangles), confort total sans éviction.',
        statsClassic: { objects: '10 000', submit: '2.50 ms', cpuFrame: '4.10 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '10 000', submit: '< 0.1 ms', cpuFrame: '0.04 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Budget VRAM', val: 'Indéfini', desc: 'Saturation GPU' },
          { label: 'Éviction', val: 'Aucune', desc: 'Consommation brute' },
          { label: 'Stuttering', val: 'Présent', desc: 'Pic initial' },
          { label: 'Contrôle', val: 'Faible', desc: 'VRAM non bornée' },
        ],
        pillsGpu: [
          { label: 'Budget VRAM', val: '128 MB', desc: 'Plafond étendu' },
          { label: 'Résident', val: '10 000 objets', desc: '5.0M tris' },
          { label: 'Temps gestion', val: '0.04 ms', desc: 'Zéro stutter' },
          { label: 'Thrashing', val: '0 boucle', desc: 'Oracle validé' },
        ],
        chartA: 2.50,
        chartB: 0.04,
      },
    ],
    benchLabel: 'Tester Streaming VRAM',
    metricsPills: [
      { label: 'Budget VRAM', val: '64 MB', desc: 'Plafond strict' },
      { label: 'Instances', val: '5 000', desc: '2.5M triangles' },
      { label: 'Temps gestion', val: '0.05 ms', desc: 'Recherche & éviction' },
      { label: 'Thrashing', val: '0 boucle', desc: 'Oracle validé' },
    ],
    stats: { objects: '5 000', submit: '< 0.1 ms', cpuFrame: '0.05 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '12-visibility-buffer': {
    id: '12-visibility-buffer',
    number: '12',
    name: 'Visibility Buffer & Shading Différé',
    subtitle: 'Raster compact (InstanceID + TriangleID, 8 octets/pixel) + reconstruction barycentrique',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'Visibility Buffer Shading',
    telemetryDetail: '8 Bytes/Pixel G-Buffer + Barycentric Interp',
    description: "Séparation totale entre rasterisation et shading : le Visibility Buffer n'écrit que 8 octets par pixel.",
    technicalPrinciple: 'Reconstruction différée des barycentriques : 1 seul shading par pixel visible sans overdraw.',
    chartTitle: 'Empreinte Mémoire G-Buffer (Mo)',
    chartUnit: 'Mo',
    options: [
      {
        val: '1080p',
        label: '⚡ Résolution 1080p (FHD)',
        selected: true,
        desc: '1080p (1920×1080) : G-Buffer standard 55.4 Mo vs Visibility Buffer 15.8 Mo (Économie 3.5x).',
        statsClassic: { objects: '2 000', submit: '1.80 ms', cpuFrame: '3.20 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '2 000', submit: '0.12 ms', cpuFrame: '0.22 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Taille G-Buf', val: '32–64 o/px', desc: 'Albedo, Norm, etc.' },
          { label: 'Bande passante', val: '55.4 MB', desc: 'G-Buffer lourd' },
          { label: 'Shading calls', val: 'Multi-passes', desc: 'Overdraw présent' },
          { label: 'Ratio VRAM', val: '1.0x', desc: 'Référence lourde' },
        ],
        pillsGpu: [
          { label: 'Taille G-Buf', val: '8 octets/px', desc: 'Instance + Triangle' },
          { label: 'Bande passante', val: '15.8 MB', desc: '−71.5% VRAM' },
          { label: 'Recon. Bary', val: '0.22 ms', desc: 'Pixel exact' },
          { label: 'Overdraw', val: '1x shading', desc: 'Zéro pixel gâché' },
        ],
        chartA: 55.4,
        chartB: 15.8,
      },
      {
        val: '1440p',
        label: 'Résolution 1440p (2K)',
        desc: '1440p (2560×1440) : G-Buffer standard 98.4 Mo vs Visibility Buffer 28.1 Mo (Économie 3.5x).',
        statsClassic: { objects: '5 000', submit: '4.20 ms', cpuFrame: '7.10 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '5 000', submit: '0.18 ms', cpuFrame: '0.35 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Taille G-Buf', val: '32–64 o/px', desc: '4x MRT textures' },
          { label: 'Bande passante', val: '98.4 MB', desc: 'Très lourd' },
          { label: 'Shading calls', val: 'Surcoût', desc: 'Overdraw 2K' },
          { label: 'Ratio VRAM', val: '1.0x', desc: 'Référence' },
        ],
        pillsGpu: [
          { label: 'Taille G-Buf', val: '8 octets/px', desc: 'Compact' },
          { label: 'Bande passante', val: '28.1 MB', desc: '−71.4% VRAM' },
          { label: 'Recon. Bary', val: '0.35 ms', desc: 'Pixel exact' },
          { label: 'Overdraw', val: '1x shading', desc: 'Zéro gâchis' },
        ],
        chartA: 98.4,
        chartB: 28.1,
      },
      {
        val: '4k',
        label: '🔥 Résolution 4K (Ultra-HD)',
        desc: '4K (3840×2160) : G-Buffer standard 221.5 Mo vs Visibility Buffer 63.3 Mo (Économie 3.5x).',
        statsClassic: { objects: '10 000', submit: '8.90 ms', cpuFrame: '14.5 ms', fps: '60 FPS', drawCalls: '1' },
        statsGpu: { objects: '10 000', submit: '0.25 ms', cpuFrame: '0.60 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Taille G-Buf', val: '32–64 o/px', desc: 'Saturation bande passante' },
          { label: 'Bande passante', val: '221.5 MB', desc: 'Chute sur mobile' },
          { label: 'Shading calls', val: 'Lourd', desc: 'Overdraw 4K' },
          { label: 'Ratio VRAM', val: '1.0x', desc: 'Référence' },
        ],
        pillsGpu: [
          { label: 'Taille G-Buf', val: '8 octets/px', desc: 'Ultra compact' },
          { label: 'Bande passante', val: '63.3 MB', desc: '−71.4% VRAM' },
          { label: 'Recon. Bary', val: '0.60 ms', desc: 'Pixel exact' },
          { label: 'Overdraw', val: '1x shading', desc: 'Zéro gâchis' },
        ],
        chartA: 221.5,
        chartB: 63.3,
      },
    ],
    benchLabel: 'Tester Visibility Buffer',
    metricsPills: [
      { label: 'Taille G-Buf', val: '8 octets/px', desc: 'vs 32–64 Deferred' },
      { label: 'Bande passante', val: '−75%', desc: 'Gain mémoire raster' },
      { label: 'Temps Recon.', val: '0.22 ms', desc: 'Barycentriques' },
      { label: 'Overdraw', val: '1x shading', desc: 'Zéro pixel gâché' },
    ],
    stats: { objects: '2 000', submit: '0.12 ms', cpuFrame: '0.22 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '13-full-gpu-driven': {
    id: '13-full-gpu-driven',
    number: '13',
    name: 'Full GPU-Driven Architecture',
    subtitle: 'Pipeline GPU unifié : Culling + LOD SSE + Hi-Z + Compaction + Multi-Draw',
    badge: 'INTEGRATE · VALIDÉ',
    telemetryMode: 'Full GPU-Driven Autonomous Pipeline',
    telemetryDetail: '100k Instances / 38.4M Triangles',
    description: "Architecture maîtresse finale synthétisant l'ensemble des 13 briques du laboratoire en un pipeline entièrement exécuté sur GPU.",
    technicalPrinciple: "Zéro intervention CPU par frame : soumission d'une commande unique dispatch + drawIndirect. Crossover absolu franchi.",
    chartTitle: 'Latence de Soumission CPU (ms)',
    chartUnit: 'ms',
    options: [
      {
        val: '50000',
        label: '50 000 instances (19.2M tri)',
        desc: '50 000 instances (19.2M triangles) : soumission Three.js 80.5 ms vs GPU-Driven 0.20 ms (Gain 402x).',
        statsClassic: { objects: '50k', submit: '80.5 ms', cpuFrame: '120 ms', fps: '8 FPS', drawCalls: '50 000' },
        statsGpu: { objects: '50k', submit: '0.20 ms', cpuFrame: '0.28 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit CPU', val: '80.5 ms', desc: '50k draw calls' },
          { label: 'Framerate', val: '8 FPS', desc: 'Gel complet' },
          { label: 'Draw calls', val: '50 000', desc: 'Soumission brute' },
          { label: 'Overhead', val: '100%', desc: 'CPU saturé' },
        ],
        pillsGpu: [
          { label: 'Instances', val: '50 000', desc: '19.2M triangles' },
          { label: 'Gain Submit', val: '402x', desc: '0.20 ms vs 80.5 ms' },
          { label: 'Draw calls', val: '1 draw', desc: 'Multi-draw' },
          { label: 'Pipeline', val: '10 étages', desc: '100% autonome' },
        ],
        chartA: 80.5,
        chartB: 0.20,
      },
      {
        val: '100000',
        label: '⚡ 100 000 objets (Pipeline complet)',
        selected: true,
        desc: '100 000 instances (38.4M triangles) : soumission Three.js 160.1 ms vs GPU-Driven 0.25 ms (Gain 640x).',
        statsClassic: { objects: '100k', submit: '160.1 ms', cpuFrame: '240 ms', fps: '4 FPS', drawCalls: '100 000' },
        statsGpu: { objects: '100k', submit: '0.25 ms', cpuFrame: '0.35 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit CPU', val: '160.1 ms', desc: '100k draw calls' },
          { label: 'Framerate', val: '4 FPS', desc: 'Effondrement total' },
          { label: 'Draw calls', val: '100 000', desc: 'Goulot Three.js' },
          { label: 'Overhead', val: '100%', desc: 'CPU saturé' },
        ],
        pillsGpu: [
          { label: 'Instances', val: '100 000', desc: '38.4M triangles' },
          { label: 'Gain Submit', val: '640x', desc: '0.25 ms vs 160 ms' },
          { label: 'Draw calls', val: '1 draw', desc: 'O(1) invariant' },
          { label: 'Pipeline', val: '10 étages', desc: 'Pipeline GPU unifié' },
        ],
        chartA: 160.1,
        chartB: 0.25,
      },
      {
        val: '200000',
        label: '🔥 200 000 instances (Torture)',
        desc: '200 000 instances (76.8M triangles) : soumission Three.js 320 ms vs GPU-Driven 0.38 ms (Gain 842x).',
        statsClassic: { objects: '200k', submit: '320.0 ms', cpuFrame: '480 ms', fps: '2 FPS', drawCalls: '200 000' },
        statsGpu: { objects: '200k', submit: '0.38 ms', cpuFrame: '0.52 ms', fps: '60 FPS', drawCalls: '1' },
        pillsClassic: [
          { label: 'Submit CPU', val: '320.0 ms', desc: 'Crash potentiel' },
          { label: 'Framerate', val: '2 FPS', desc: 'Inutilisable' },
          { label: 'Draw calls', val: '200 000', desc: '200k draws' },
          { label: 'Overhead', val: 'Critique', desc: 'CPU gelé' },
        ],
        pillsGpu: [
          { label: 'Instances', val: '200 000', desc: '76.8M triangles' },
          { label: 'Gain Submit', val: '842x', desc: '0.38 ms vs 320 ms' },
          { label: 'Draw calls', val: '1 draw', desc: 'O(1) invariant' },
          { label: 'Pipeline', val: '10 étages', desc: '100% stable' },
        ],
        chartA: 320.0,
        chartB: 0.38,
      },
    ],
    benchLabel: 'Vérifier le pipeline complet',
    painLabel: 'Stress Torture 200k Instances',
    metricsPills: [
      { label: 'Instances', val: '100 000', desc: '38.4M triangles' },
      { label: 'Temps CPU', val: '0.35 ms', desc: 'Boucle frame totale' },
      { label: 'Submit CPU', val: '0.25 ms', desc: 'vs >150 ms WebGL' },
      { label: 'GPU Frame', val: '2.92 ms', desc: '>340 FPS théorique' },
    ],
    stats: { objects: '100k', submit: '0.25 ms', cpuFrame: '0.35 ms', fps: '60 FPS', drawCalls: '1' },
  },
  '14-open-world': {
    id: '14-open-world',
    number: '14',
    name: 'Monde ouvert sous pression',
    subtitle: 'Scène Bistro résidente, pression de rendu WebGL2',
    badge: 'MESURABLE',
    telemetryMode: 'Three.js WebGL2 résident',
    telemetryDetail: 'Bistro répété en quartiers',
    description: 'Rendu Three.js WebGL2 résident : une scène Bistro répétée en quartiers mesure la pression de rendu et de culling, avec la géométrie déjà chargée en mémoire.',
    technicalPrinciple: 'Géométrie résidente. Ce banc ne met pas en œuvre de géométrie virtualisée.',
    options: [
      { val: '1', label: '1 quartier' },
      { val: '9', label: '9 quartiers', selected: true },
      { val: '25', label: '25 quartiers' },
    ],
    benchLabel: 'Mesurer et comparer',
    painLabel: 'Arrêter',
    metricsPills: [],
    stats: { objects: '9 quartiers', submit: 'Non mesuré', cpuFrame: 'Non mesuré', fps: 'Non mesuré', drawCalls: 'Non mesuré' },
  },
};
